package com.wodejia.myapp.data;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.wodejia.myapp.data.AccountDO;
import com.wodejia.myapp.table.AreasDO;

import com.wodejia.myapp.data.AccountDODao;
import com.wodejia.myapp.table.AreasDODao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig accountDODaoConfig;
    private final DaoConfig areasDODaoConfig;

    private final AccountDODao accountDODao;
    private final AreasDODao areasDODao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        accountDODaoConfig = daoConfigMap.get(AccountDODao.class).clone();
        accountDODaoConfig.initIdentityScope(type);

        areasDODaoConfig = daoConfigMap.get(AreasDODao.class).clone();
        areasDODaoConfig.initIdentityScope(type);

        accountDODao = new AccountDODao(accountDODaoConfig, this);
        areasDODao = new AreasDODao(areasDODaoConfig, this);

        registerDao(AccountDO.class, accountDODao);
        registerDao(AreasDO.class, areasDODao);
    }
    
    public void clear() {
        accountDODaoConfig.clearIdentityScope();
        areasDODaoConfig.clearIdentityScope();
    }

    public AccountDODao getAccountDODao() {
        return accountDODao;
    }

    public AreasDODao getAreasDODao() {
        return areasDODao;
    }

}
