package com.wodejia.myapp.table;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.wodejia.myapp.data.DaoSession;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BLOCK_DO".
*/
public class BlockDODao extends AbstractDao<BlockDO, Long> {

    public static final String TABLENAME = "BLOCK_DO";

    /**
     * Properties of entity BlockDO.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property BlockId = new Property(0, long.class, "blockId", true, "_id");
        public final static Property BlockName = new Property(1, String.class, "blockName", false, "BLOCK_NAME");
        public final static Property BlockIcon = new Property(2, String.class, "blockIcon", false, "BLOCK_ICON");
    }


    public BlockDODao(DaoConfig config) {
        super(config);
    }
    
    public BlockDODao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BLOCK_DO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL ," + // 0: blockId
                "\"BLOCK_NAME\" TEXT," + // 1: blockName
                "\"BLOCK_ICON\" TEXT);"); // 2: blockIcon
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BLOCK_DO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, BlockDO entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getBlockId());
 
        String blockName = entity.getBlockName();
        if (blockName != null) {
            stmt.bindString(2, blockName);
        }
 
        String blockIcon = entity.getBlockIcon();
        if (blockIcon != null) {
            stmt.bindString(3, blockIcon);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, BlockDO entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getBlockId());
 
        String blockName = entity.getBlockName();
        if (blockName != null) {
            stmt.bindString(2, blockName);
        }
 
        String blockIcon = entity.getBlockIcon();
        if (blockIcon != null) {
            stmt.bindString(3, blockIcon);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public BlockDO readEntity(Cursor cursor, int offset) {
        BlockDO entity = new BlockDO( //
            cursor.getLong(offset + 0), // blockId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // blockName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // blockIcon
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, BlockDO entity, int offset) {
        entity.setBlockId(cursor.getLong(offset + 0));
        entity.setBlockName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setBlockIcon(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(BlockDO entity, long rowId) {
        entity.setBlockId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(BlockDO entity) {
        if(entity != null) {
            return entity.getBlockId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(BlockDO entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
